import { jsPDF } from 'jspdf';
import { ValidationResult } from '@compliance-hub/shared';

export interface ComplianceReportOptions {
    validationResult: ValidationResult;
    fileHash: string;
    timestamp: string;
}

/**
 * Generate Official ViDA / EN 16931 Compliance Audit PDF Report
 * Structure:
 * 1. Cover - Title, timestamp, file hash
 * 2. File Metadata
 * 3. ViDA Score (0-100)
 * 4. EN 16931 Checklist
 * 5. DRR / Business Rules
 * 6. Executive Summary
 */
export function generateComplianceReportPDF(options: ComplianceReportOptions): ArrayBuffer {
    const { validationResult: result, fileHash, timestamp } = options;

    const doc = new jsPDF();

    // Helper: safe text
    const safeText = (text: string): string => {
        if (!text) return '';
        return text
            .replace(/[""]/g, '"')
            .replace(/['']/g, "'")
            .replace(/–/g, '-')
            .replace(/—/g, '--')
            .replace(/…/g, '...')
            .replace(/✓/g, '[OK]')
            .replace(/✗/g, '[X]')
            .replace(/[^\x00-\x7F]/g, '?');
    };

    // Calculate status
    const score = result.vida?.score || 0;
    const status: 'ready' | 'needs_fixes' | 'not_compliant' =
        result.valid && score >= 80 ? 'ready' :
            result.valid || score >= 50 ? 'needs_fixes' : 'not_compliant';

    // ========================
    // PAGE 1: COVER
    // ========================

    // Header line
    doc.setDrawColor(44, 82, 130);
    doc.setLineWidth(2);
    doc.line(20, 25, 190, 25);

    // Title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(24);
    doc.setTextColor(44, 82, 130);
    doc.text('ViDA / EN 16931', 105, 50, { align: 'center' });
    doc.text('Compliance Audit', 105, 62, { align: 'center' });

    // Official badge
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text('OFFICIAL COMPLIANCE REPORT', 105, 80, { align: 'center' });

    // Status badge
    doc.setFontSize(18);
    if (status === 'ready') {
        doc.setTextColor(34, 197, 94);
        doc.text('[OK] READY FOR COMPLIANCE', 105, 110, { align: 'center' });
    } else if (status === 'needs_fixes') {
        doc.setTextColor(251, 146, 60);
        doc.text('[!] NEEDS FIXES', 105, 110, { align: 'center' });
    } else {
        doc.setTextColor(239, 68, 68);
        doc.text('[X] NOT COMPLIANT', 105, 110, { align: 'center' });
    }

    // Score display
    doc.setFontSize(48);
    const scoreColor = score >= 80 ? [34, 197, 94] : score >= 50 ? [251, 146, 60] : [239, 68, 68];
    doc.setTextColor(...scoreColor);
    doc.text(`${score}`, 105, 150, { align: 'center' });

    doc.setFontSize(14);
    doc.setTextColor(100, 100, 100);
    doc.text('ViDA Compliance Score (out of 100)', 105, 162, { align: 'center' });

    // Metadata box
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.5);
    doc.rect(30, 180, 150, 45);

    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.text('Report Metadata', 35, 190);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(`Timestamp (UTC): ${timestamp}`, 35, 200);
    doc.text(`File SHA-256: ${fileHash.slice(0, 32)}...`, 35, 210);
    doc.text(`Profile: EN 16931 v2 / Peppol BIS 4.0`, 35, 220);

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text('Generated by ViDA UBL Validator | vida.bauklar.com', 105, 270, { align: 'center' });
    doc.text('This report is not stored. File hash ensures authenticity.', 105, 278, { align: 'center' });

    // ========================
    // PAGE 2: DETAILED RESULTS
    // ========================
    doc.addPage();

    let y = 25;

    // Header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(44, 82, 130);
    doc.text('Validation Results', 20, y);
    y += 15;

    // Statistics
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);

    const errorCount = result.errors?.length || 0;
    const warningCount = result.warnings?.length || 0;
    const infoCount = result.infos?.length || 0;

    doc.text(`Errors: ${errorCount}`, 20, y);
    doc.text(`Warnings: ${warningCount}`, 70, y);
    doc.text(`Infos: ${infoCount}`, 120, y);
    y += 15;

    // ViDA Checklist
    if (result.vida?.checklist && result.vida.checklist.length > 0) {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(14);
        doc.setTextColor(44, 82, 130);
        doc.text('EN 16931 / ViDA Checklist', 20, y);
        y += 10;

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);

        for (const item of result.vida.checklist) {
            if (y > 270) {
                doc.addPage();
                y = 25;
            }

            const statusText = item.passed ? '[OK]' : '[X]';
            const color = item.passed ? [34, 197, 94] : [239, 68, 68];

            doc.setTextColor(...color);
            doc.text(statusText, 20, y);

            doc.setTextColor(0, 0, 0);
            doc.text(safeText(item.title || 'Check'), 35, y);

            if (item.description) {
                y += 5;
                doc.setFontSize(8);
                doc.setTextColor(100, 100, 100);
                const lines = doc.splitTextToSize(safeText(item.description), 160);
                doc.text(lines, 35, y);
                y += lines.length * 3;
                doc.setFontSize(10);
            }

            y += 8;
        }

        y += 10;
    }

    // Errors section
    if (errorCount > 0) {
        if (y > 240) {
            doc.addPage();
            y = 25;
        }

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(14);
        doc.setTextColor(239, 68, 68);
        doc.text(`Errors (${errorCount})`, 20, y);
        y += 10;

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);

        for (const [index, error] of (result.errors || []).entries()) {
            if (y > 265) {
                doc.addPage();
                y = 25;
            }

            doc.setTextColor(200, 0, 0);
            doc.text(`${index + 1}.`, 20, y);

            doc.setTextColor(0, 0, 0);
            const ruleId = safeText(error.id || error.ruleId || 'N/A');
            doc.text(`Rule: ${ruleId}`, 30, y);
            y += 5;

            const message = safeText(error.message || 'No description');
            const lines = doc.splitTextToSize(message, 160);
            doc.text(lines, 30, y);
            y += lines.length * 4;

            if (error.hint) {
                doc.setFontSize(8);
                doc.setTextColor(0, 100, 0);
                doc.text(`Fix: ${safeText(error.hint)}`, 30, y);
                y += 4;
                doc.setFontSize(9);
            }

            y += 4;
        }

        y += 10;
    }

    // Warnings section
    if (warningCount > 0) {
        if (y > 240) {
            doc.addPage();
            y = 25;
        }

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(14);
        doc.setTextColor(251, 146, 60);
        doc.text(`Warnings (${warningCount})`, 20, y);
        y += 10;

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);

        for (const [index, warning] of (result.warnings || []).entries()) {
            if (y > 265) {
                doc.addPage();
                y = 25;
            }

            doc.setTextColor(200, 100, 0);
            doc.text(`${index + 1}.`, 20, y);

            doc.setTextColor(0, 0, 0);
            const ruleId = safeText(warning.id || warning.ruleId || 'N/A');
            doc.text(`Rule: ${ruleId}`, 30, y);
            y += 5;

            const message = safeText(warning.message || 'No description');
            const lines = doc.splitTextToSize(message, 160);
            doc.text(lines, 30, y);
            y += lines.length * 4;

            if (warning.hint) {
                doc.setFontSize(8);
                doc.setTextColor(0, 100, 0);
                doc.text(`Fix: ${safeText(warning.hint)}`, 30, y);
                y += 4;
                doc.setFontSize(9);
            }

            y += 4;
        }
    }

    // ========================
    // EXECUTIVE SUMMARY (last page)
    // ========================
    doc.addPage();

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor(44, 82, 130);
    doc.text('Executive Summary', 20, 30);

    doc.setLineWidth(0.5);
    doc.line(20, 35, 190, 35);

    // Summary box
    doc.setFillColor(status === 'ready' ? 240 : status === 'needs_fixes' ? 255 : 255,
        status === 'ready' ? 255 : status === 'needs_fixes' ? 250 : 240,
        status === 'ready' ? 240 : status === 'needs_fixes' ? 240 : 240);
    doc.rect(20, 45, 170, 40, 'F');

    doc.setFontSize(14);
    if (status === 'ready') {
        doc.setTextColor(34, 197, 94);
        doc.text('[OK] READY FOR ViDA COMPLIANCE', 105, 60, { align: 'center' });
        doc.setFontSize(11);
        doc.setTextColor(60, 60, 60);
        doc.text('This invoice meets EN 16931 v2 and ViDA requirements.', 105, 72, { align: 'center' });
    } else if (status === 'needs_fixes') {
        doc.setTextColor(251, 146, 60);
        doc.text('[!] NEEDS FIXES BEFORE SUBMISSION', 105, 60, { align: 'center' });
        doc.setFontSize(11);
        doc.setTextColor(60, 60, 60);
        doc.text(`Address ${errorCount} error(s) and ${warningCount} warning(s) to achieve compliance.`, 105, 72, { align: 'center' });
    } else {
        doc.setTextColor(239, 68, 68);
        doc.text('[X] NOT COMPLIANT', 105, 60, { align: 'center' });
        doc.setFontSize(11);
        doc.setTextColor(60, 60, 60);
        doc.text('Major issues found. Review all errors before resubmission.', 105, 72, { align: 'center' });
    }

    // Key metrics
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);

    doc.text('Key Metrics:', 20, 105);
    doc.text(`- ViDA Score: ${score}/100`, 25, 115);
    doc.text(`- Errors: ${errorCount}`, 25, 125);
    doc.text(`- Warnings: ${warningCount}`, 25, 135);
    doc.text(`- Validation Profile: EN 16931 v2`, 25, 145);

    // Disclaimer
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text('Disclaimer:', 20, 170);
    const disclaimer = 'This report is generated based on automated validation rules. ' +
        'It does not constitute legal compliance certification. ' +
        'Always verify with your tax authority or compliance officer.';
    const disclaimerLines = doc.splitTextToSize(disclaimer, 170);
    doc.text(disclaimerLines, 20, 180);

    // Footer on all pages
    const pageCount = doc.internal.pages.length - 1;
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(
            'Official ViDA Compliance Report | vida.bauklar.com',
            20,
            287
        );
        doc.text(`Page ${i} of ${pageCount}`, 175, 287);
    }

    // Return as ArrayBuffer
    return doc.output('arraybuffer');
}

/**
 * Calculate SHA-256 hash of file content
 */
export async function calculateFileHash(content: string): Promise<string> {
    const encoder = new TextEncoder();
    const data = encoder.encode(content);
    const hashBuffer = await crypto.subtle.digest('SHA-256', data);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}
